version: '3'
services:
  s3:
    image: fsouza/fake-gcs-server@sha256:91afded49de804aa61b5f3eb6c7cd65205acf9e5c5e047cf0ba7d9507af806c8
    entrypoint: [ "/bin/fake-gcs-server", "-data", "/data", "-scheme", "http" ]
    ports:
      - "50000:4443"
