apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "dp-mellomlagring"
  namespace: "teamdagpenger"
  labels:
    "team": "teamdagpenger"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "internal/isalive"
  readiness:
    path: "internal/isready"
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 75
  prometheus:
    enabled: true
    path: "/internal/metrics"
  limits:
    cpu: "750m"
    memory: "1024Mi"
  requests:
    cpu: "500m"
    memory: "512Mi"
  envFrom:
    - secret: dp-mellomlagring-config
  secureLogs:
    enabled: true
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  accessPolicy:
    outbound:
      rules:
        - application: clamav
          namespace: clamav
    inbound:
      rules:
        - application: dp-soknadsdialog
        - application: dp-behov-soknad-pdf
        - application: dp-behov-journalforing
        - application: dp-vaktmester-mellomlagring
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  env:
    - name: DP_MELLOMLAGRING_BUCKETNAME
      value: {{bucketName}}
  gcp:
    permissions:
      - resource:
          apiVersion: kms.cnrm.cloud.google.com/v1beta1
          kind: KMSCryptoKey
          name: /locations/europe-north1/keyRings/dp-mellomlagring/cryptoKeys/dp-mellomlagring
        role: roles/cloudkms.cryptoKeyEncrypterDecrypter
    buckets:
      - name: {{ bucketName }}
