apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "dp-mellomlagring"
  namespace: "teamdagpenger"
  labels:
    "team": "teamdagpenger"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "internal/isalive"
  readiness:
    path: "internal/isready"
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/internal/metrics"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  envFrom:
    - secret: dp-mellomlagring-config
  secureLogs:
    enabled: false
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  accessPolicy:
    outbound:
      rules:
        - application: clamav
          namespace: clamav
    inbound:
      rules:
        - application: dp-soknadsdialog
        - application: dp-behov-soknad-pdf
        - application: dp-behov-journalforing
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  env:
    - name: TOKEN_X_ACCEPTED_AUDIENCE
      value: {{TOKEN_X_ACCEPTED_AUDIENCE}}
    - name: DP_MELLOMLAGRING_BUCKETNAME
      value: {{bucketName}}
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: KMSCryptoKey
          name: /locations/europe-north1/keyRings/dp-mellomlagring/cryptoKeys/dp-mellomlagring
          role: roles/cloudkms.cryptoKeyEncrypterDecrypter
    buckets:
      - name: {{ bucketName }}
        retentionPeriodDays: 90
        lifecycleCondition:
          age: 7
          numNewerVersions: 2
          withState: ANY
