apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "dp-mellomlagring"
  namespace: "teamdagpenger"
  labels:
    "team": "teamdagpenger"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "internal/isalive"
  readiness:
    path: "internal/isready"
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  envFrom:
    - secret: dp-mellomlagring-config
  secureLogs:
    enabled: false
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: dp-quizshow-api
  tokenx:
    enabled: true
  env:
    - name: TOKEN_X_ACCEPTED_AUDIENCE
      value: {{acceptedAudience}}
    - name: DP_MELLOMLAGRING_BUCKETNAME
      value: {{bucketName}}
  gcp:
    buckets:
      - name: {{ bucketName }}
        retentionPeriodDays: 90
        lifecycleCondition:
          age: 7
          numNewerVersions: 2
          withState: ANY
