apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "dp-mellomlagring"
  namespace: "teamdagpenger"
  labels:
    "team": "teamdagpenger"
spec:
  image: {{image}}
  port: 8080
  liveness:

  readiness:
    path: "internal/isready"
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  secureLogs:
    enabled: false
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: dp-quizshow
  gcp:
    buckets:
      - name: {{ bucketName }}
        retentionPeriodDays: 90
        lifecycleCondition:
          age: 7
          numNewerVersions: 2
          withState: ANY
